### ISSUE TITLE
[Help] ERROR: `Generic paremeter 'T' could not be infered` on simple get request

### ISSUE THREAD

**Issue by luatnd** [Gujci/RESTAPI#10]
I try to fire a simple get request in README but cannot build, it raises me an error:

![image](https://user-images.githubusercontent.com/1859127/95811587-cbe6d180-0d3d-11eb-9f1a-3443dd0a176c.png)

How can I fix it?
Thanks for your help.

**Comment by luatnd** [comment]
I can get it to work from this guide: https://github.com/Gujci/RESTAPI#request-with-expected-response-type 

But it would be nice if I don't need to define my response type.

**Comment by Gujci** [comment]
@luatnd You got the correct answer. Right now the response type is something that may be a response (conforming to a given protocol). If you want to omit the type, we have to find out what a default type would be. It can be `Data`, `JSON` ...etc.  Right now I can live with both. Any suggestions?

**Comment by luatnd** [comment]
After some several development use cases, I prefer `Expected Response Type` :D, the lib is good enough.

I think the reason I got the issue is the guide:

> testServerApi.get("/posts") { (**`status, data`**) in
>    //This data will be SwiftyJSON's Optional JSON type by default (data: JSON?)
> }

A little modification in README would prevent further accident:
> testServerApi.get("/posts") { (**`status: ResponseStatus, data: JSON?`**) in

**Comment by Gujci** [comment]
Yep, It stuck in from the old times, I guess. Thank you for pointing it out, I have fixed it. Also, it got me thinking to update other parts of the README as well. 

If you have any other comments on the docs, fell free to reopen this issue or open an other one.
