### ISSUE TITLE
Any hope for Cocoapods?

### ISSUE THREAD

**Issue by MaeseppTarvo** [Gujci/RESTAPI#2]
Title says it all :) Awesome work btw.

**Comment by Gujci** [comment]
@MaeseppTarvo Thanks. I have switched fully to `Carthage`, so it is not on the roadmap _yet_.

## Solution 1

 I may consider adding that sometime, but do not count on it.
 You can implement it in a fork, then submit a pull request, so I can accept it and have the feature 😄 

## Solution 2

If you don't mind modifying your project structure, `Cocoapods` and `Cathage` can exist together in one project, but I personally hate to use multiple dependency managers.

**Comment by Gujci** [comment]
@MaeseppTarvo Thanks for the contribution.
