### ISSUE TITLE
Error on trying to start project with RESTAPI (installed via cocoa pods)

### ISSUE THREAD

**Issue by MatiMil** [Gujci/RESTAPI#4]
Hi,

thanks for your work!
Today I started a new app and installed your project via cocoa pods. So far so good.
Then I tried to start my app (like I said its a clean app with just a tabbar controller).

After starting I got this error message:
"Call can throw, but it is not marked with 'try' and the error is not handled" in API.swift on line 186 on "JSON(data: validData)".
Maybe it is because swiftyJson changed some things too and the function you call is now "throwable" ?

I solved it by adding "try?".

Thanks for your help and your awesome work.

Best regards

Mati

**Comment by Gujci** [comment]
Hi,

I think this may be related to incompatible versions. I don't really use CocoaPods, so the `podspec` file is not maintained unfortunately.

However, i found that the `REASTAPI.podspec`file is still linking to the '0.3.7' version, when the newest is '0.9.2'. I have upgraded this, so it might work now. I hope it does not have to be registered to cocoapods.org again.

Please try it again.

**Comment by MatiMil** [comment]
Hi,

thanks for your fast response. That didnt quite fix the problem.

Here is a picture what and where I get it:
[Error Picture](http://i66.tinypic.com/2zsms60.png)

Here is the picture with fix:

[Prolem Solved Picture](http://i68.tinypic.com/20aayc0.png)

To recreate the problem just create an iOS Project -> in terminal do pod init -> than add pod 'RESTAPI' -> try to run project -> error

So I think if you could just add my fix like in the picture this could solve the problem.
Bu I am actually not sure because I didnt do a lot of swift :)


Thanks!

**Comment by MatiMil** [comment]
Ah now I get it I got the wrong version. This is the problem :D sorry. Didnt catch that at first. Well podspec didnt fixe it but i will look into this and find out why it is installing an old version in cocoa pods

**Comment by Gujci** [comment]
I think the whole registration to the Cocoapods repository is out of date. (https://cocoapods.org/pods/RESTAPI) I have to upgrade it soon.

**Comment by MatiMil** [comment]
Yes I see it. Thanks for your fast responses.

Just so I know will you update this on cocoapods?

**Comment by Gujci** [comment]
Apparently, I'm not allowed to update the pod repo, since @MaeseppTarvo has the ownership of the pod repository.

So, I see 2 solutions right now:

*  Reaching out to @MaeseppTarvo, to update the pod repo.
*  Use something else than cocoapods. [Carthage](https://github.com/Carthage/Carthage) can be added to a pod projecs as well, but it requires more manual steps. On the upside, it's not central, so none of the stupid permission issues would happen, which makes updating a framework impossible for the code owner.

**Comment by MatiMil** [comment]
Hi,

thank you for your answers I found another solution. Add this to your podfile.
pod 'RESTAPI', :git => 'https://github.com/Gujci/RESTAPI.git'

I didnt know that @MaeseppTarvo hold the rights for this pod.
If you add the git link in your podfile it will get this version here.

Maybe you can just update your readme on this github projects so others know.

Thanks you for helping me!
This is now fixed for me

**Comment by Gujci** [comment]
Thank you! I have updated the readme file accordingly.
